### ISSUE TITLE
Downloaders Not working

### ISSUE THREAD

**Issue by bcritical** [SokunHeng/DownEdit#1]
The downloaders not working, 
Editing video working well, 

Just request, if availible to download video and thumbnail together.

For editing maybe we can custom the audio Thank you

**Comment by SokunHeng** [comment]
Hi, which downloader is not working well? Could you be more specific?
And what kind of features do you request in a video editor? Could you be more specific?
I've also updated the introduction, which you can read [here](https://github.com/SokunHeng/DownEdit#readme). Thanks
