### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by daltonjames777** [sokunheng/DownEdit#20]
For tiktok it only downloads 30 videos how can you insert cookies to allow downloading more videos, adding a download from https://musicaldown.com/ in HD format would be amazing,(You use > https:// www.kuaishou.com/ and https://www.videofk.com/) these changes would improve the code on Git Hub and recommend it everywhere.

**Comment by SokunHeng** [comment]
Thank you for your valuable input and suggestions. We definitely appreciate your interest in making our project better.

In terms of downloading more than 30 videos from TikTok, it might be limited by the API we are using by certain restrictions to prevent abuse. However, it may be possible to circumvent these limits by using cookies or some form of session management.

Adding support for HD downloads from musicaldown.com sounds like a great idea! We would need to inspect the site's structure and how it handles video files. It's also important to note that the technical feasibility will depend on whether they expose any accessible interfaces or APIs that we can use to fetch the video data. For the sites you mentioned (kuaishou.com and videofk.com), if there are specific functionalities or strategies that you think we could learn from, we would love to hear more details.

If you feel confident in your coding skills, contributions to the codebase are always welcome. You can clone the repository, make your changes, and submit a pull request. Thank you again for your interest and suggestions. We look forward to making this project better with the help of contributors like you. 🤩

**Comment by SokunHeng** [comment]
Thank you for your valuable input and suggestions. We definitely appreciate your interest in making our project better.

Regarding the limit of 30 videos from TikTok, that's down to the restrictions of the API we're currently using, it's a safeguard against abuse. However, we're exploring ways around these constraints. The use of cookies, cursors, or other forms of session management may be the answer.

The idea of adding support for HD downloads from musicaldown.com sounds awesome! There's a little work needed on our end to understand the site's structure and how it manages video files, but we love a challenge. Keep in mind that whether we can pull this off depends on the availability of accessible interfaces or APIs on their end. For the sites you mentioned (kuaishou.com and videofk.com), if there are specific functionalities or strategies that you think we could learn from, we would love to hear more details.

If you feel confident in your coding skills, we'd love to see your contributions to the project! Feel free to clone the repository, make your tweaks, and submit a pull request. We're all about community collaboration here. Once again, big thanks for your keen interest and valuable suggestions. 🤩
