### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by nupican** [sokunheng/DownEdit#23]
![Screenshot_3](https://github.com/sokunheng/DownEdit/assets/130196786/eec83430-3577-4a6b-8c36-79622406801e)

hello my friend, how to solve the error in your tool, please help me, I need your tool.
I really appreciate you replying to my message
thank you

**Comment by watashiyoga** [comment]
i got this too

![image](https://github.com/sokunheng/DownEdit/assets/6204441/edd3705c-dfc3-4076-a3b4-2599881568bc)

**Comment by sokunheng** [comment]
Hi there, just checking in about the error. Is everything still working okay?

**Comment by cas-melo** [comment]
having the same issue. any fix?
