### ISSUE TITLE
Down edit isnt working

### ISSUE THREAD

**Issue by iankitkapoor01** [sokunheng/DownEdit#39]
i tried running it but it is not working it would be really appreciated if you provide your email and i can contact you to show you the issue.

**Comment by sokunheng** [comment]
Hi [iankitkapoor01](https://github.com/iankitkapoor01). This project is still in development. Please follow and star the project for updates on upcoming releases. Thank you for your patience!

**Comment by OwElko** [comment]
download is working , edits not working alwasy throw errors

**Comment by sokunheng** [comment]
Hi @OwElko, Editing feature is currently in development and encountering errors. However, you can still use the function for now.

**Comment by rockahmed** [comment]
NameError' object is not subscriptable when click on tiktok download

**Comment by sokunheng** [comment]
Hi @rockahmed, TikTok is currently being reworked. Thanks for your patience!
